@echo off
echo clean up output folder...
del js\* /Q
echo compile IENotification...
call tsc ts/IENotification.ts --outDir js/ -target es5 --sourceMap
echo compile less files...
call lessc less/notification.less css/notification.css --source-map
echo done...